definitions:
  ginx.Response:
    properties:
      data: {}
      message:
        type: string
      requestID:
        type: string
    type: object
  serializer.UserCreateRequest:
    properties:
      name:
        maxLength: 32
        minLength: 1
        type: string
    required:
    - name
    type: object
  serializer.UserListResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
      updater:
        type: string
    type: object
info:
  contact: {}
  description: 蓝鲸开发者中心 SaaS 后台 API 文档
  title: BkApp API DOC
  version: 1.0.0
paths:
  /api/Users:
    get:
      operationId: list_users
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/serializer.UserListResponse'
                  type: array
              type: object
      summary: 查询user列表
      tags:
      - user
    post:
      operationId: create_user
      parameters:
      - description: 创建用户请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.UserCreateRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 新增用户
      tags:
      - user
swagger: "2.0"
